### ISSUE TITLE
[bug] 게임 점수가 음수, 삼각형의 점수 반영 X

### ISSUE THREAD

**Issue by algoORgoal** [JONHYOJIN/Gaining-Territory#2]
![image](https://github.com/JONHYOJIN/Gaining-Territory/assets/19303532/032ed8c6-c947-48a9-a1aa-056eccf7cce9)

1. cancel 여러번을 했더니 machine의 점수가 음수로 바뀌었습니다. 실격 처리를 하기 위하여 의도된 것인지 궁금합니다. 
2. [(5,0)(6,1)] 선분을 그었고, [(3,6),(5,6)] 선분을 그었는데 색칠도 되지 않았고 점수도 올라가지 않았습니다. 점수가 올라가고 색칠도 되는 것이 올바른 동작 아닌가요?

**Comment by algoORgoal** [comment]
cancel 버튼을 여러번 누를 시에 문제가 발생하는 것 같습니다. cancel을 여러번 눌렀을 때 turn이 user와 machine으로 계속 번갈아서 변경됩니다.

**Comment by JONHYOJIN** [comment]
1. Cancel은 바로 이전 수로 돌아가기 위한 버튼입니다. 따라서 Cancel을 한 번에 여러 번 진행하게 되면 시스템이 꼬이게 됩니다. 추가적으로 한 번에 2점을 얻은 경우에도 Cancel을 사용하면 시스템이 꼬이게 됩니다. 이 점 유의해주시면 좋을 것 같습니다.
2. Cancel을 여러 번 눌러 시스템이 꼬인 것으로 보입니다. Cancel을 누르지 않았는데도 위 현상이 발생하면 다시 말씀 해주시면 원인을 해결해 보도록 하겠습니다.

**Comment by algoORgoal** [comment]
cancel을 여러번 누를 경우를 전제하지 않고 만들어진 시스템이란 것 인지했습니다. 답변 감사합니다.
